kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sentinelops
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
      - containerPort: 443
        hostPort: 8443
        protocol: TCP
      # Grafana NodePort 30030 -> host :3000
      - containerPort: 30030
        hostPort: 3000
        protocol: TCP
  - role: worker
  - role: worker
containerdConfigPatches:
  # Trust local insecure registry on host
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
        [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
          endpoint = ["http://kind-registry:5000"]
